version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: SecureImageTransmissionAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

  client:
    build: 
      context: .
      dockerfile: SecureImageTransmissionClient/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork: